name: Spotless Check

# Trigger the workflow on push events to any branch
on:
  push:
    branches:
      - '**'

jobs:
  spotless:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # Cache Maven dependencies to speed up the build
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      # Run Spotless check
      - name: Run Spotless Check
        run: mvn spotless:check

      # Fail if Spotless finds formatting issues and report them
      - name: Fail if Spotless finds issues
        run: |
          echo "::error file=Spotless found issues. Run mvn spotless:apply to fix them."
        if: failure()
